#!/usr/bin/env node
// Lift exact UI components out of an HTML design export into a campaign, so popouts
// match the approved design pixel-for-pixel instead of being rebuilt by hand.
//
//   node scripts/extract-design.mjs <export.html> <campaign> name=<css selector> [name=<selector> ...]
//   node scripts/extract-design.mjs ~/Downloads/design/Screens.html spring-launch \
//     taskCard='#shot-1 > div:nth-child(4)' resultPill='#shot-1 > div:nth-child(5)'
//
// Writes campaigns/<campaign>/design.ts exporting { parts: { name: { html, width } } }.
// Use in a scene: <Pop html={parts.taskCard.html} width={parts.taskCard.width} scale={2.2} .../>
//
// Works best with exports that use inline styles (Claude Design, most "export to HTML"
// tools). Pages styled by external CSS classes (Tailwind apps) won't carry their styles;
// rebuild those surfaces with src/kit/ui.tsx or use real screenshots instead.
// Images are inlined as data URIs (JPEGs downscaled) so frames never wait on a load.
// The page is rendered in headless Chrome first, so script-built designs work too.
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { ensureBrowser } from "@remotion/renderer";
import puppeteer from "puppeteer-core";

const [file, campaign, ...pairs] = process.argv.slice(2);
if (!file || !campaign || !pairs.length) {
  console.error("usage: node scripts/extract-design.mjs <export.html> <campaign> name=<selector> [...]");
  process.exit(1);
}
const root = path.resolve(import.meta.dirname, "..");
const htmlPath = path.resolve(file);
const selectors = Object.fromEntries(pairs.map((p) => [p.slice(0, p.indexOf("=")), p.slice(p.indexOf("=") + 1)]));

const browserInfo = await ensureBrowser();
const exe = browserInfo?.path ?? process.env.CHROME_PATH;
const browser = await puppeteer.launch({ executablePath: exe, args: ["--allow-file-access-from-files"] });
const page = await browser.newPage();
await page.setViewport({ width: 4000, height: 3000, deviceScaleFactor: 0.25 });
await page.goto("file://" + htmlPath, { waitUntil: "networkidle0" });
await new Promise((r) => setTimeout(r, 1500));
const parts = await page.evaluate((sel) => {
  const out = {};
  for (const [name, s] of Object.entries(sel)) {
    const el = document.querySelector(s);
    if (!el) throw new Error(`no element matches ${name}=${s}`);
    out[name] = { html: el.outerHTML, width: el.offsetWidth };
  }
  return out;
}, selectors);
await browser.close();

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "extract-"));
const inline = (src) => {
  const abs = path.resolve(path.dirname(htmlPath), src);
  if (!fs.existsSync(abs)) return src;
  if (/\.(png|svg|gif|webp)$/i.test(abs) && fs.statSync(abs).size < 200_000) {
    const mime = abs.endsWith(".svg") ? "image/svg+xml" : `image/${path.extname(abs).slice(1).toLowerCase()}`;
    return `data:${mime};base64,${fs.readFileSync(abs).toString("base64")}`;
  }
  const out = path.join(tmp, path.basename(abs) + ".jpg");
  try {
    execFileSync("ffmpeg", ["-loglevel", "error", "-y", "-i", abs, "-vf", "scale='min(700,iw)':-2", "-q:v", "4", out]);
    return `data:image/jpeg;base64,${fs.readFileSync(out).toString("base64")}`;
  } catch {
    return `data:image/png;base64,${fs.readFileSync(abs).toString("base64")}`;
  }
};
for (const p of Object.values(parts)) {
  p.html = p.html.replace(/src="(?!data:|https?:)([^"]+)"/g, (_, s) => `src="${inline(s)}"`);
}
const dest = path.join(root, "campaigns", campaign, "design.ts");
fs.mkdirSync(path.dirname(dest), { recursive: true });
fs.writeFileSync(
  dest,
  `// Generated by scripts/extract-design.mjs from ${path.basename(htmlPath)}. Re-run it instead of hand-editing.\n` +
    `export const parts: Record<string, { html: string; width: number }> = ${JSON.stringify(parts)};\n`,
);
console.log(`${path.relative(root, dest)}: ${Object.keys(parts).join(", ")}`);
